english_corpus_dir: ../PascalSentenceDataset/english/
japanese_corpus_dir: ../PascalSentenceDataset/wakati/
japanese_original_corpus_dir: ../PascalSentenceDataset/japanese/
img_features_npy: pascal_features_g.npy
img_original_dir: ../PascalSentenceDataset/dataset/
img_correspondence_path: ../PascalSentenceDataset/correspondence.csv
